### ISSUE TITLE
Перемещение объекта из массива в массив

### ISSUE THREAD

**Issue by Rendol** [matreshkajs-ru/matreshkajs-ru.github.io#1]
Продолжу нашу беседу по этому вопросу https://github.com/finom/matreshka/pull/7 здесь.

Вариант `bindRenderedAsSandbox: false` - не вариант. В элементе я заложился на то, что выборка элементов блока идет от песочницы. И это очень здорово.

Вариант `array.push_( item, { moveSandbox: true })` мне больше нравится.

Так как идеологией развития библиотеки владеете только Вы, то Вам принимать решение =)
Жду Вашего решения.

**P.S.** Это очень важный момент. Столкнулся с ним при реализации перемещения узла с потомками в дереве.

**Comment by finom** [comment]
Спасибо за помощь. Я приму решение в скором.
