### ISSUE TITLE
Ошибка в документации

### ISSUE THREAD

**Issue by undermuz** [matreshkajs-ru/matreshkajs-ru.github.io#3]
Здравствуйте, Андрей.
У вам опечатка/ошибка в документации:

``` javascript
// метод shift добавляет функцию в начало массива Matreshka.defaultBinders
Matreshka.defaultBinders.shift( function( node ) {
    // проверяем, является ли элемент чекбоксом
    if( node.tagName == 'INPUT' && node.type == 'checkbox' ) {
        // если проверка пройдена, возвращаем новый байндер
        return Matreshka.binders.checkbox();
    }
});
```

Метод shift - удаляет первый элемент массива, а не добавляет в начало, http://javascript.ru/Array/shift
Тут имелся ввиду метод unshift, http://javascript.ru/Array/unshift

Эта ошибка в нескольких местах в документации

**Comment by finom** [comment]
Здравствуйте, 
Спасибо. Неприятная ошибка. Скоро выкачу новую версию сайта с этим исправлением.
