### ISSUE TITLE
RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by undermuz** [matreshkajs-ru/matreshkajs-ru.github.io#4]
Изолированный пример бага: http://jsfiddle.net/rwmgn07h/3/
Скрин в сафари: http://joxi.ru/D2PQwRaunOWlA3

Баг проявляется в сафари 8 при вызове функции мадиатора

**Comment by finom** [comment]
Вижу, спасибо. Странный баг. Даже в старых Ослах такого не наблюдается.

**Comment by finom** [comment]
Пификсил. CDN требует немного времени, чтобы обновиться.
